version: '3.3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "test"
    ports:
      - "3314:3306"
